name: edinet-tdnet cloud run

on:
  # 手動実行（Web/スマホアプリから）
  workflow_dispatch:
    inputs:
      start:        { description: '開始日 YYYY-MM-DD', required: true }
      end:          { description: '終了日 YYYY-MM-DD', required: true }
      codes:        { description: '会社名または4桁コード(カンマ区切り) 例: 7203,ソニー', required: false, default: '' }
      filetypes:    { description: 'EDINETファイル種別 csv,pdf,xbrl', required: false, default: 'pdf' }
      include_yuho: { description: '有報 yes/no', required: false, default: 'yes' }
      include_q:    { description: '四半期 yes/no', required: false, default: 'no' }
      tdnet:        { description: 'TDnet(短信) yes/no', required: false, default: 'yes' }

  # JST 09:10（= UTC 00:10）に毎日自動実行したい場合は有効化
  schedule:
    - cron: '10 0 * * *'

permissions: { contents: read }
concurrency: { group: edinet-tdnet, cancel-in-progress: true }

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run downloader
        env:
          EDINET_API_KEY: ${{ secrets.EDINET_API_KEY }}
        run: |
          python edinet_tdnet_downloader.py \
            --start "${{ github.event.inputs.start }}" \
            --end   "${{ github.event.inputs.end }}" \
            --edinet-filetypes "${{ github.event.inputs.filetypes }}" \
            --include-yuho "${{ github.event.inputs.include_yuho }}" \
            --include-quarter "${{ github.event.inputs.include_q }}" \
            --tdnet "${{ github.event.inputs.tdnet }}" \
            --codes "${{ github.event.inputs.codes }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          path: downloads
          retention-days: 90
